platform :ios, '8.0'
#use_frameworks!
target 'JYProject' do
pod 'MBProgressHUD', '~> 0.9.2'
pod 'AFNetworking', '~> 3.1.0'
pod 'MJRefresh', '~> 3.1.0'
pod 'SDWebImage', '~> 3.7.5'
pod 'Masonry', '~> 1.0.1'
pod 'YYModel', '~> 1.0.4'
pod 'YYCache', '~> 1.0.4'
pod 'MJExtension', '~> 3.0.10' #这个有毒 删除一堆警告
pod 'ReactiveObjC', '~> 3.0.0'
end
