platform :ios, '8.0'
#use_frameworks!个别需要用到它，比如reactiveCocoa

target 'JYProject' do

pod 'MBProgressHUD', '~> 0.9.2'
pod 'AFNetworking', '~> 3.1.0'
pod 'MJRefresh', '~> 3.1.0'
pod 'MJExtension', '~> 3.0.10'
pod 'SDWebImage', '~> 3.7.5'
pod 'Masonry', '~> 1.0.1'

end
